-- ============================================================================
-- PRDISE — seed.sql (VACÍO INTENCIONAL)
-- ============================================================================
--
-- 2026-06-09: el cliente entregará un Excel con el catálogo real. Para que
-- `supabase db reset --linked` no repoble la DB con contenido demo, este
-- archivo queda vacío.
--
-- El template completo con stays/tours/vehicles/routes/partners/posts demo
-- vive en `supabase/seed.example.sql` por si se necesita restaurar un dataset
-- de prueba para QA. Para usarlo:
--   $ cp supabase/seed.example.sql supabase/seed.sql
--   $ npx supabase db reset --linked
--
-- TABLAS QUE SÍ SE POBLAN AUTOMÁTICAMENTE (vía migraciones, no este seed):
--   * permissions (granular permission keys)
--   * site_settings (whatsapp_phone, contact_email, etc. con defaults)
-- ============================================================================

-- Sin INSERTs. La carga del catálogo real se hará a partir del Excel del
-- cliente cuando llegue.
