import { chromium } from 'playwright';
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1280, height: 900 } });
await c.addInitScript(() => localStorage.setItem('prdise_lang', JSON.stringify('es')));
const p = await c.newPage();
await p.goto('http://127.0.0.1:4173/login', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(3500);
await p.locator('input[type="email"]').first().fill('admin@livinginprdise.com');
const pw = p.locator('input[type="password"]').first();
await pw.fill('admin@livinginprdise.com');
await pw.press('Enter');
await p.waitForTimeout(3500);
await p.locator('button:has-text("Tours")').first().click();
await p.waitForTimeout(1500);
await p.locator('.adm-pcard-btn:has-text("Editar"), .adm-pcard-btn:has-text("Edit")').first().click();
await p.waitForTimeout(2000);
await p.locator('button:has-text("Español")').first().click().catch(() => {});
await p.waitForTimeout(300);
const ta = p.locator('label:has-text("Notas Importantes") + textarea').first();
const cur = await ta.inputValue();
const cleaned = cur.replace(/\n?e2e-persist-\w+/g, '').trim();
await ta.fill(cleaned);
await p.locator('button:has-text("Guardar")').first().click();
await p.waitForTimeout(3500);
console.log('cleanup done, before=', JSON.stringify(cur.slice(-60)), 'after=', JSON.stringify(cleaned));
await b.close();
